#%RAML 1.0 NamedExample

value:
  customerID: "1"
  fName: "Laa"
  lName: "Max"
  phoneNumber: 202-144-1201
  SSN: 123-45-6789
  customerAddress:
    {
      address: "1919 9th St",
      city: "washington",
      state: "DC",
      zip_code: "20012"
    }


